add_rules("mode.debug", "mode.release")
add_requires("glad", "glfw")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})
set_languages("c++20")
target("robolab")
    set_policy("run.autobuild", true)
    set_kind("binary")
    add_files("src/*.cpp", "src/**/*.cpp")
    add_includedirs("include")
    add_packages("glad", "glfw")  